// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjarstbcqijtwypzilis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqYXJzdGJjcWlqdHd5cHppbGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODc4MjUsImV4cCI6MjA3MTk2MzgyNX0.K7zoRxmCNobadzI_p9DFKcY9u4AW6F9Axn6YkeCbX_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});